### ISSUE TITLE
User Auth remote-url

### ISSUE THREAD

**Issue by koog1000** [koog1000/vscode-fossil#1]
In the fossil init workflow the user password is passed as part of the `remote-url`. This should be passed to stdin with a corresponding `-y` to store password securely in repo.

**Comment by senyai** [comment]
At least with fossil-2.18 the password is stored securely and it is not becoming a part of `remote-url`. But it's still passed as plaintext to the executable. Should we still try to pass the password to stdin?

**Comment by koog1000** [comment]
My memory is hazy on this, but you can't actually put the password to stdin. When fossil asks for your password it dynamically creates a new input stream to capture the password. I wasn't sure how to get this through vscode.

**Comment by senyai** [comment]
Related stackoverflow question: [Why can't getpass take input from stdin?](https://stackoverflow.com/questions/66846759/what-cant-getpass-take-input-from-stdin)

**Comment by senyai** [comment]
Currently it's not possible to use stdin on unix ([see fossil forum post](https://fossil-scm.org/forum/forumpost/8c535d85fb)). Maybe someday someone will change this behavior in fossil itself, but till then I close this issue.
