### ISSUE TITLE
can't get it to work

### ISSUE THREAD

**Issue by pekeler** [koog1000/vscode-fossil#12]
I have an open fossil repo and been committing from the cmd-line. After installing this extension, it didn't seem to notice changes I made to a file. So I restarted VSCode (`code .` within my checked out project) which promptly gave me the error 'current directory is not within an open checkout'. Shortly after, my fan got noisy - looked like that was due to 3 fossil processes running. Restarting VSCode again, I'm not getting the error msg anymore but it always launches 3 fossil processes that max out my CPU. Meanwhile, using fossil from the cmd-line is still fine.

I wonder if this extension perhaps has some expectations that aren't true here? For example, does it expect a remote URL? (I'm just using fossil locally). Or does it expect the .fossil file to be in the opened project? (Mine is somewhere else). Or does it need me to check out the repo again, through the extension?

MacOS 10.14.6
VSCode 1.38.1
fossil 2.10
koog1000.fossil 0.0.11

**Comment by vor0nwe** [comment]
Version 0.0.11 doesn't work at all for me, either. Try installing version 0.0.10, that works fine on my machine.

In the list of extensions, click the ⚙ gear icon next to the 'Fossil' extension in the list, then choose 'Install other version'):
![image](https://user-images.githubusercontent.com/76925/66288107-4766a500-e8d8-11e9-8076-0bb90b64ab7d.png)

**Comment by pekeler** [comment]
Thanks @vor0nwe - 0.0.10 does seem to get a bit further. It looks like it's doing `fossil extra` instead of `fossil extra .` and the result is so overwhelming, it stops working.
<img width="653" alt="ss" src="https://user-images.githubusercontent.com/42363/66323209-a92b0d00-e8e0-11e9-9f7d-0f95f88f193a.png">

**Comment by koog1000** [comment]
You have more than 654,000 additional files in your repo? Surely most of those can be ignored. Do you have an ignore-glob file setup?

**Comment by pekeler** [comment]
My repo has 4 files.

**Comment by pekeler** [comment]
After changing my project's root to have fewer extras, v0.0.10 seems to work for me. Thanks!
