### ISSUE TITLE
Plugin throws error when opening a non-fossil project

### ISSUE THREAD

**Issue by tobykurien** [koog1000/vscode-fossil#14]
Repeatedly throws this error when in a project that is not using Fossil:

```
Fossil: use --repository or -R to specify the repository database
```

The error cannot be dismissed as it will keep trying to refresh and throw the error again, meaning one has to disable or uninstall the plugin.

**Comment by koog1000** [comment]
This will be fixed shortly. Someone else saw this yesterday but I haven't had a chance to update yet.

**Comment by koog1000** [comment]
v0.0.13 should be up in the marketplace in a few minutes.
