### ISSUE TITLE
pull broken

### ISSUE THREAD

**Issue by pekeler** [koog1000/vscode-fossil#152]
### Desire

10

### Help

- [X] Discuss
- [X] Test
- [ ] Code

### Steps to reproduce

1. upgrade to 0.4.0
2. Pull
3. see the following error output:

> fossil update https://myname@mydomain.com/: 128ms
> cannot resolve name: https://myname@mydomain.com/

### Description

Worked fine in the previous version. Continuous to work from the command line in the same checkout.

### OS

Mac OS 13.4.1

### Fossil version

2.22

### Vscode/Vscodium version

1.82.2

**Comment by pekeler** [comment]
I never specify the remote host when using pull or update from the command line.
`fossil remote list` shows just one default URL, which is the same from the error message. and when I manually do `fossil update THE_REMOTE_URL`, I get the same error message "cannot resolve name".

Is this even a legal parameter to `fossil update`? It doesn't look like it to me judging from `fossil help update`.

**Comment by senyai** [comment]
Yes, funny enough it still fails with 'cannot resolve name:'. I will release a quick fix in 6 hours, sorry for the inconvenience. I blame `fossil.autoUpdate` option that changes how "pull" behaves and this option is there from 'vscode-hg' plugin and makes little sense in fossil world. I believe I will have to rename 'Pull' to 'Update' to be in fossil terms.

**Comment by senyai** [comment]
Extension is ready. There are now two separate commands 'Pull' and 'Update', hope it will  make more sense for everyone now.

**Comment by pekeler** [comment]
0.5.0 fixes the issue - thanks. However, pull is still broken for me, it's just less of an issue because I typically just use update.

The problem is that `fossil pull URI` is prompting for a password that fossil doesn't seem to remember even though I tell it to. Now using pull from VSCode, I don't even get prompted for the password and just get "missing or incorrect password for user ...".

Again, not a priority for me since update is working now.

**Comment by senyai** [comment]
@pekeler can you check something for me? `fossil remote list` will print NAME and URI. I guess if one does `fossil pull URI` and not `fossil pull NAME` then the saved password is not used.

**Comment by pekeler** [comment]
`default` being one of the names? Yes, `fossil pull default` does not prompt me for the password and works from the command line.

**Comment by senyai** [comment]
That's what I thought. I see name usage is not mentioned it the docs anywhere and that's why I used the uri format. Will ask about it on fossil forum.
