### ISSUE TITLE
viewing diff of deleted file

### ISSUE THREAD

**Issue by pekeler** [koog1000/vscode-fossil#157]
### Desire

1

### Help

- [ ] Discuss
- [ ] Test
- [ ] Code

### Steps to reproduce

1. `fossil rm file`
2. `rm file`
3. click Refresh button in VSCode's source control section
4. select the red, deleted file
5. see "The editor could not be opened due to an unexpected error: Unexpected token 'e', "empty" is not valid JSON"

### Description

Viewing a deleted file in the diff view causes problems.

### Vscode/Vscodium version

0.5.2

**Comment by senyai** [comment]
Fixed in 0.5.3. New behavior matches git extension. I don't quite like it (because it just shows file content), but I couldn't figure out how to make better.
