### ISSUE TITLE
Unable to install extension from vscode extension store

### ISSUE THREAD

**Issue by sahil48** [koog1000/vscode-fossil#19]
![image](https://user-images.githubusercontent.com/6100774/70061586-82bce180-15b2-11ea-8ac4-9a1d88cfe26a.png)

When I clicked install manually, I was refered to the following link which was not available.

https://marketplace.visualstudio.com/_apis/public/gallery/publishers/koog1000/vsextensions/fossil/0.0.19/vspackage

**Comment by koog1000** [comment]
When I click that link the vsix package is downloaded. Try it again and let me know.

**Comment by sahil48** [comment]
Installation now works. Thanks.

Server providing the downloaded file must have had a temporary outage. Thanks.
