### ISSUE TITLE
 git/github export [enhancement]

### ISSUE THREAD

**Issue by vinniec** [koog1000/vscode-fossil#20]
Maybe it's not a good idea, but I'm just trying to hypothesize it, would it make sense to add support to this? https://fossil-scm.org/home/doc/trunk/www/mirrortogithub.md
I don't know if it makes sense since the integration isn't complete, but it might be nice to keep a repository always updated on github while using fossil.

**Comment by koog1000** [comment]
This is an interesting proposition. I've used this feature a couple times.

Ultimately it requires that you use fossil >= 2.9 and I don't think everyone uses that. I'm not wanting to build in version dependencies and this is still a relatively new version.

**Comment by koog1000** [comment]
The version dependency has come up in a couple other decision I have made (I think branch/tag options changed at some point) and I am opting to keep as generic as possible.

**Comment by vinniec** [comment]
Well, it's wise even though it may happen that some versions will be almost obligatory sooner or later.
I my regards, i don't using anything special so I just took the latest version and I'm using that one, but I think other people might have other problems.

**Comment by koog1000** [comment]
Most of the Linux distros are not on 2.9 or 2.10, I suppose once the default packages in the major distros is up to 2.9 then I can safely add this feature without worrying about versioning issues.

**Comment by vinniec** [comment]
I think yours is a good idea and fortunately we can control it and not just make supposition!:
https://repology.org/projects/?search=fossil&maintainer=&category=&inrepo=&notinrepo=&repos=&families=&repos_newest=&families_newest=

From what I understand the number at the top distinguishes repository families, so currently 26 families have a version >= 2.9 and 34 lower.
Now admitting that many of them won't change anyway (9 families are < 2) I'd say we're on the right track!

**Comment by Yorizuka** [comment]
> I wonder what exactly should be done in this extension. Transform `mirrortogithub.md` into a wizard?

Not sure what the best idea is, For users who are familiar with fossil this is a non issue, but as someone who has had to introduce people to fossil, anything that reduces friction for new users is very valuable. While it may seem silly I think a wizard helps remove intimidation for new users. So even if it is not directly beneficial for older fossil users, this may be a relatively easy way to help with the adoption and onboarding process.

**Comment by senyai** [comment]
Hi @vinniec! I wanted to let you know that version 0.5.7 now includes a new feature for exporting to GitHub or Git. To access this feature, you can go to the Command Palette and select the option "Publish to GitHub/Git".

This feature utilizes the GitHub API to create a new repository and then publishes it using the `fossil git export` command.

If you're still interested, I encourage you to check out this new version. If everything works as expected, we can consider closing the issue.

**Comment by senyai** [comment]
According to the extension tests, this feature is fully implemented.
