### ISSUE TITLE
Can you add the ability to connect to a existing repo?

### ISSUE THREAD

**Issue by dbadaddy** [koog1000/vscode-fossil#22]
I have a fossil repo, and I want to connect to it in vscode. But I don't see a way to do that in the config. When I try it tells me that the file already exists and stops there. 
Please do the needful, and add this ability.

Thank You.

**Comment by koog1000** [comment]
Can you give me some more context about what you mean when you say you want to 'connect' to a fossil repo? If you're asking how to view the scm content in VSCode then all you need to do is open a folder that is part of a fossil repository. If you've done that then the scm tab will show you the repository info and the status bar will show your current branch.

**Comment by koog1000** [comment]
I assume you figured out how to do what it is that you were trying. I'm going to close this ticket.
