### ISSUE TITLE
Please make this extension available in the marketplace for 64-bit ARM.

### ISSUE THREAD

**Issue by tidux** [koog1000/vscode-fossil#23]
This would allow, for example, a Raspberry Pi 4 to use it.

**Comment by koog1000** [comment]
What exactly do I need to do to do that? As far as I know there's nothing in the code base that is x86 specific.

**Comment by tidux** [comment]
I've got https://github.com/cdr/code-server running on an aarch64 Linux machine and searching for Fossil returns no extension results.

**Comment by tidux** [comment]
I think a good workaround would be building the .vsix for every Github release of the extension.

**Comment by koog1000** [comment]
ok, I just tried this out on my rpi4. The vscode fossil extension install no problem.

**Comment by koog1000** [comment]
I do build the vsix for every release of vscode, and upload the build to the marketplace.
