### ISSUE TITLE
missing user name

### ISSUE THREAD

**Issue by aschoepe** [koog1000/vscode-fossil#24]
If fossil user name is not the same as login user name.
For example "commit -user <user name> ..."
Maybe that can be added to workspace config settings.

**Comment by koog1000** [comment]
Good observation. So you use a repository that synchronizes with the remote as a different user than yourself? Is this a multi-user machine where you only have one clone (accessible by all users) and then individual users checkout in their user space? What other configuration settings may be needed in this case?

**Comment by aschoepe** [comment]
This is exactly how it is. My local user name is "baz". The user name of the external repo is "foo".
fossil clone https://foo@example.org/repos/fossil/repo repo.fossil
I think it is important to make the settings workspace or for ssh connections dependent on the working directory.

**Comment by aschoepe** [comment]
It is really great that we can use fossil through this plugin! I have two more remarks, I will create one more case for each. Thanks for this plugin!

**Comment by koog1000** [comment]
I just made a new release with the username configuration option - should be updated in VSCode Marketplace in a minute. Let me know if it doesn't work for you.
