### ISSUE TITLE
ignore-glob setting is not considered when showing untracked files

### ISSUE THREAD

**Issue by richieadler** [koog1000/vscode-fossil#25]
No files matching the glob patterns in this setting should be shown as "untracked" as they are explicitly excluded.

**Comment by koog1000** [comment]
It works as expected on my machine. To get the untracked files the extension calls `fossil extras`, which should only list untracked files that are not ignored. Can you describe your specific issue?

**Comment by richieadler** [comment]
Sorry, it was a false alarm. I had a problem refreshing the view after a change in configuration.
