### ISSUE TITLE
Constant remainder of file not in any repo

### ISSUE THREAD

**Issue by mp81ss** [koog1000/vscode-fossil#26]
Every time I save a file that does not belong to any repo, a pop-up rises, telling "file outside of checkout tree"
I know it, and I'm not going to add it to any repo. I find it quite annoying.

I propose 2 possible fixes:
1. Emit the message one time only per file
1. Add an option in settings (ignore/one time only/all)

**Comment by koog1000** [comment]
Interesting, I use VScode quite often outside of a fossil repo and I don't see those warnings pop up. Can you describe your specific situation? My guess would be that you have multiple folders open in a workspace and one is an open fossil checkout and the other isn't?

**Comment by mp81ss** [comment]
I currently have 6 files opened, 4 are in the same fossil repo, and two are in another completely different folder
The pop-up rises even when I switch to those files, and when I save them too.
Hope this help

**Comment by koog1000** [comment]
Ok, I'm trying this out on my machine and I can't get it to show the errors like you are describing. I have a fossil repo open and have open files outside of that repo and I am not getting popup warnings about the files outside the repo.

Can you give me the specific steps to reproduce?

**Comment by koog1000** [comment]
I assume that you have resolved the issues you were having. Let me know if you find anything else.
