### ISSUE TITLE
how to create new branches?

### ISSUE THREAD

**Issue by maphew** [koog1000/vscode-fossil#27]
What's the recommended way to create new branches from with the fossil extension? I can see how to change branches but not create.

_Thanks for this extension! So glad I found it._

**Comment by koog1000** [comment]
You can create branches from the command palette. Ctrl+Shift+P and start typing "fossil: create branch" and you'll get to the option. I _think_ you can add a custom keybinding for that as well.

**Comment by maphew** [comment]
Wonderful, that works (I'm new to vscode also, still getting used to having a command palette at all let alone one that includes extension commands). And yes r-click while in the `Ctrl-Shift-P` results brings up a context menu to create and remove keybindings.

![image](https://user-images.githubusercontent.com/486200/127265219-ab259b53-d134-462e-85e2-f93d90673e29.png)
