### ISSUE TITLE
There's no undo in the editor

### ISSUE THREAD

**Issue by senyai** [koog1000/vscode-fossil#29]
Hi! Great extension!
With git extension I see "undo" button in this window:
![image](https://user-images.githubusercontent.com/76137/132470565-2bfa24db-cfbc-4567-a84e-4bf6927bfa21.png)
to the left of the "↓" button. It's not there with vscode-fossil extension.

**Comment by koog1000** [comment]
I'll be honest, I have no idea how to add that. My first thought is that it may be some special feature of git (similar to git add --patch, but in reverse). If you can point me towards some documentation I can modify the code to add it.

**Comment by senyai** [comment]
I made some investigations. [Subversion plugin](https://github.com/JohnstonCode/svn-scm/) also supports this feature and the class is called `RevertChange`. This class is located [here](https://github.com/JohnstonCode/svn-scm/blob/master/src/commands/revertChange.ts)  and is added to the window title [here](https://github.com/JohnstonCode/svn-scm/blob/master/package.json). Hope this helps, if not I will have to setup dev environment.
