### ISSUE TITLE
commit never completes when fossil asks questions

### ISSUE THREAD

**Issue by pekeler** [koog1000/vscode-fossil#30]
I just tried to commit a binary without having a binary-glob around, and the progress bar kept on going forever while there was no indication in the fossil output pane of the underlying issue. This worked fine once I added the binary-glob and killed/restarted VSCode, but would be really neat if the prompts from fossil would be translated into some interactive graphical prompt. I wonder if any other VSCode plugin already has a generic solution for translating stdin-prompts into a GUI that could be copied.

**Comment by koog1000** [comment]
Can you please provide the steps to reproduce? I just tested this and it worked as expected (input prompt with the question, that I answered and the commit finished)

Steps to test:
```
fossil init test.fossil
fossil open test.fossil --workdir ./test
cd ./test
# make a binary file
python3 -c "f = open('test.bin', 'wb'); f.write(bytes(list(range(255)))); f.close()"
code ./test
```
After VSCode opens you can use the SCM pane to add and commit the test.bin file. At that point you should get a new webview with the full description and an additional input prompt with the question, and after answering the question the commit should finish.

**Comment by pekeler** [comment]
Thank you for the helpful steps (the last line should be just `code .`, though). I can't reproduce it anymore, either. I repeated the test in my other repo where I had the problem after deleting the binary-glob, and there it's working now, too.

However (different issue), when typing 'N' and return into the prompt, I see the same symptom now - the progress bar that doesn't stop.

**Comment by koog1000** [comment]
I don't see that on my end. Entering N causes the commit to fail (which is expected) and an error notification is displayed with the message that the commit failed because of the binary data.

**Comment by pekeler** [comment]
Strange. I'm using VSCode 1.60.1 with Fossil 0.1.0 and fossil 2.16 on Mac OS 11.5.2.
