### ISSUE TITLE
Feature request: spawn Fossil web interface in webview tab

### ISSUE THREAD

**Issue by tidux** [koog1000/vscode-fossil#31]
One of the many things I like about Fossil is the integrated web interface with all the integrated functionality.  VSCode is built on a web stack.  Embedding the web UI inside VSCode would allow much more work to remain fully within the IDE.  The shell command that normally starts a default browser is `fossil ui`, so that could be intercepted and the port (8080 by default) opened in a webview tab.

**Comment by koog1000** [comment]
Duplicates #41
