### ISSUE TITLE
Bug: renamed files don't appear in the changes tab

### ISSUE THREAD

**Issue by tidux** [koog1000/vscode-fossil#32]
How to reproduce:

1. Open integrated terminal.
2. `$ fossil rename foo bar`
3. Both foo and bar disappear from the Source Control tab, despite not being committed changes yet.

**Comment by senyai** [comment]
Hi! Can you provide the state of the repository before you did `$ fossil rename foo bar`? What were the states of the `foo` and `bar` when they were in Source Control tab?

**Comment by senyai** [comment]
The fix is on its way. I will need not more that four days.
