### ISSUE TITLE
Release v0.1.1

### ISSUE THREAD

**Issue by senyai** [koog1000/vscode-fossil#38]
Hi! I'm sure the world is ready for the new release.

**Comment by senyai** [comment]
@koog1000 Can you make me a maintainer of this project, please?

**Comment by senyai** [comment]
I've found the [publishing instruction](https://code.visualstudio.com/api/working-with-extensions/publishing-extension). I'll be back in two days and will look into that.

**Comment by senyai** [comment]
It's `senyai`.

**Comment by koog1000** [comment]
Sorry, I stated username, but I meant user id. It is a hex string, for example my vscode user id is `904855b2-0929-6a5e-833a-fc1b4421f358`

**Comment by senyai** [comment]
I don't understand where to look for this uuid. @koog1000 can you give me some instructions?

**Comment by koog1000** [comment]
https://docs.microsoft.com/en-us/visualstudio/extensibility/walkthrough-publishing-a-visual-studio-extension?view=vs-2022#troubleshoot-adding-a-user-to-the-publisher-account Just hover over your name in the marketplace

**Comment by senyai** [comment]
Mine is 9013b734-074e-4b44-8137-06ebc77fdebd

**Comment by koog1000** [comment]
Ok, see if you can get in to publish now.

**Comment by senyai** [comment]
Thank you. I will be able to have a look in 36 hours.

**Comment by senyai** [comment]
[I did it](https://marketplace.visualstudio.com/items?itemName=koog1000.fossil)! The extension was just verified. Still waiting for it to appear inside vscode.

**Comment by jamel-tirari** [comment]
Great News. it's online and i just downloaded it.
Confirmed the show file history button is perfectly functionnal ^^ thanks alot.
