### ISSUE TITLE
fossil executable not found, although in PATH

### ISSUE THREAD

**Issue by holgerjakobs** [koog1000/vscode-fossil#4]
After installing the extension (and even re-starting code), "no source control providers registered." remains. 

$ type fossil
fossil is /usr/local/bin/fossil

So fossil is installed and well (have been using it for years, and recently updated to the latest version). Where and how can I tell the extension where it resides - and why does the extension not use the PATH?

**Comment by koog1000** [comment]
The scm providers only work when VS Code is opened to a folder (or if you're using multiroot with a workspace). Did you open VS Code to a folder?

The only time you should have to tell the extension where fossil is is if it's not in your $PATH, but it looks like you have that correct so I'm assuming it is the issue above.

**Comment by koog1000** [comment]
@holgerjakobs  Were you able to figure this out? If not, can you be more explicit about the steps to reproduce, because it works as expected on my machine.
