### ISSUE TITLE
Feature request: integrate webui

### ISSUE THREAD

**Issue by tidux** [koog1000/vscode-fossil#41]
A button to launch the results of `fossil ui` in a simple webview would allow the entire Fossil workflow to be done without leaving VSCode.

**Comment by senyai** [comment]
Has anyone seen any extensions implementing something similar?

**Comment by tidux** [comment]
https://marketplace.visualstudio.com/items?itemName=ms-vscode.live-server does a dynamic webview connected to a backend server process.

**Comment by senyai** [comment]
Even though showing web ui in vscode is a nice idea, vscode itself wasn't designed to handle this case (yet). In command palette there's 'Simple Browser: show' command that never worked for me - just shows white screen for any url. [The docs](https://code.visualstudio.com/api/extension-guides/webview) hint that website hosting shouldn't be done. Not only that, more questions must be answered: who shows browser ui (back/forward/url bar)? How to handle webview when it is hosted in a browser ([code-serever](https://github.com/coder/code-server))? How should it work in a remote-container case? I though there must be a way to do it, (ideally using cgi backend) but alas I haven't found it yet.

**Comment by alensiljak** [comment]
> A button to launch the results of `fossil ui` in a simple webview would allow the entire Fossil workflow to be done without leaving VSCode.

Why not simply launch the default browser? What is the benefit of integrating this into a code editor vs using tools specialized for doing it?

**Comment by senyai** [comment]
Fossil does not allow the opening of its web pages within an iframe ([X-Frame-Options: SAMEORIGIN](https://fossil-scm.org/home/file?ci=version-2.24&name=src/cgi.c&ln=526)) and that is why I'm closing this issue as "not planned". Use command palette to run "Fossil: Open web UI" command, it will execute `fossil ui` in a separate terminal, which is pretty convenient.
