### ISSUE TITLE
Git is shown as SCM instead of Fossil

### ISSUE THREAD

**Issue by jbshirk** [koog1000/vscode-fossil#42]
I'm just beyond the install phase. I've committed and staged everything that I had open in git.

According to help, this is what I should see:
![source control fossil](https://user-images.githubusercontent.com/3949396/168654332-5ba6afca-5d7a-4d10-baa5-efdda2927dfc.JPG)

But instead, this is what I see:
![source control git](https://user-images.githubusercontent.com/3949396/168654394-f7a916f1-8121-46d4-89c0-0501ae92d8b2.JPG)

According to settings, Fossil is enabled. It seems git is pre-empting fossil in the vscode UI, or I have skipped something important.

**Comment by senyai** [comment]
Hello. Thank you for the report. I just opened Git, SVN and fossil in the same directory and indeed fossil is not in the list. I will look into that.

**Comment by senyai** [comment]
On the other hand, I forgot to call `fossil open`. And now I see all three repos:
![image](https://user-images.githubusercontent.com/76137/168664531-120c8d96-5ad0-4039-8570-26db3e7a25c8.png)
Is your repository initialized? Have you ran `fossil new repository-name.fossil` *and* `fossil open repository-name.fossil`?
