### ISSUE TITLE
Feature request: TimeLine Support

### ISSUE THREAD

**Issue by jamel-tirari** [koog1000/vscode-fossil#47]
Hello,

Is it possible to support the default TIMELINE of VScode, i.e showing all the history of the file in this section :
![image](https://user-images.githubusercontent.com/40656336/174045141-32ea1ca2-e554-4212-b756-c031cd04a518.png)

This would allow to make diffs between specified commits (the current mecanism : show file history button, allows for diffs between the selected commit and the local copy only).

Thanks in advance.

Best Regards,

**Comment by senyai** [comment]
This is a nice feature, but I couldn't find any [api](https://code.visualstudio.com/api/references/vscode-api) for it. There's an open vscode [issue](https://github.com/microsoft/vscode/issues/84297) about it. Sadly, will have to close this one, at least for now.

**Comment by jamel-tirari** [comment]
Thanks for checking this out, i didn't know that it wasn't possible (yet). I hope that the vscode team fixes the issue of the TimeLine API.

Also, to mitigate the main issue (showing diffs of commits differently), i had some ideas for making the history system better (i don't know if it's feasible) : 

1. First Idea : add a context menu popup to the list of the commits shown by the "show file history" button that contains different actions like : 
       - Compare with previous : to make a diff of what happened on that specific commit (like in the fossil ui)
       - Select for compare : to select that commit as the first file to diff and then the list of commits is re-shown to select the second one for the diff.

2. Second idea : do the above but using keyboard shortcuts, i,e :
       - When selecting a commit while pressing a key (Ctr for example), execute the "Compare with previous" action : to make a diff of what happened on that specific commit (like in the fossil ui)
       - When selecting a commit while pressing another key (Shift for example), execute the "Select for compare" action : to select that commit as the first file to diff and then the list of commits is re-shown to select the second one for the diff.

Feel free to create a new issue if one of the ideas above seams feasible and interesting to work on and implement in the extension.

Thanks in advance for your efforts,

Best Regards,

**Comment by senyai** [comment]
There are many other issues that should be tackled before I can move on to this task. It will have to wait.

**Comment by senyai** [comment]
I'm prototyping this feature now. 'Fossil: show file history...' will show file timeline like before, but reformatted:
![image](https://user-images.githubusercontent.com/76137/179298530-6dff0ece-5c0f-4a86-80a1-5882e5aee644.png)
when clicked, another menu will pop up:
![image](https://user-images.githubusercontent.com/76137/179299793-3a9b4b2b-e2e8-4849-b7b1-f5ac1d88df01.png)
@jamel-tirari, what do you think?

**Comment by jamel-tirari** [comment]
Thank you very much for this prototype, it look great and i think it's a great solution.

I have one question : when you choose current, it does the diff with the local copy including the current changes (like the current functionning of the button) or it does the diff with the latest committed version in the current branch ?

Thanks again for your time spend on this issue.

Best Regards,

**Comment by senyai** [comment]
`current` is a [special fossil tag name](https://fossil-scm.org/home/doc/trunk/www/checkin_names.wiki) that corresponds to current checkout. Let me reword the items. Even more there's a tag named `tip` that I can add to the lists.

![image](https://user-images.githubusercontent.com/76137/179368482-6db8a6e3-4d37-4538-b7ad-c6b0a306ef1c.png)

I hope it's clear enough now. I will make next release with this feature in a week or two.

**Comment by jamel-tirari** [comment]
Thanks for the explication and the added tip tag it's great.
Yes it's clear and thanks in advance for the next release.
