### ISSUE TITLE
Feature Request: blame

### ISSUE THREAD

**Issue by aschoepe** [koog1000/vscode-fossil#62]
Show when each line of the file was last modified.

https://fossil-scm.org/home/help?cmd=blame

**Comment by senyai** [comment]
I saw nice looking blame in [GitLence](https://github.com/gitkraken/vscode-gitlens/tree/main/src/annotations). It will take some time to implement.

**Comment by koog1000** [comment]
I started some work on this long ago. There is a branch in this repo that might have something working, of course you'll want to clean it up.

**Comment by senyai** [comment]
Let me close this issue because there's some blame functionality in 0.2.4.

**Comment by aschoepe** [comment]
Perfect, I have already tried it. Super. Thank you.
