### ISSUE TITLE
When adding a previously untracked file, automatically stage it

### ISSUE THREAD

**Issue by vor0nwe** [koog1000/vscode-fossil#7]
In v0.0.9, when I want to commit a hitherto untracked file, I have to do this in two steps:
* add the file,
* then stage it.

Only then can I commit it.  
I expected this to be done in a single step.

It's not a _huge_ deal, but I can't think of a situation where I _wouldn’t_ want a newly added file to be staged.

**Comment by koog1000** [comment]
We'll have to think a out this some more. In my workflow I use the `fossil clean` command on a semi-regular basis and sometimes want to add a file so it doesn't get cleaned but not commit it right away.

**Comment by vor0nwe** [comment]
Ah, yes. Personally, I hardly ever use `fossil clean`.

But since there's a legitimate reason _not_ to stage the new file straight away, you can leave it as it is. I don't know if it's quite important enough to warrant a configuration option for this (perhaps if more people vote for this 😊).

**Comment by jungle-boogie** [comment]
I'm fine for files first needing to be added to the extension before staging. Sometimes I may want to toss a file in the same directory/repo but not commit it. If this enhancement were added, I would need to remember to remove the file first.

ya know...my workflow would be broken!!! https://xkcd.com/1172/
