### ISSUE TITLE
Add option to ignore file from context menu of untracked files.

### ISSUE THREAD

**Issue by vor0nwe** [koog1000/vscode-fossil#8]
In the Source Control pane, sometimes untracked files (extra files, in Fossil parlance) show up that I don't want to add to the repository, nor do I want it to keep cluttering the list of untracked files.

It would be nice if there were an option to 'Ignore' the file, right there from the file(s)'s context menu.
In Fossil, a file can be ignored with the setting [`ignore-glob`](https://www.fossil-scm.org/fossil/help?cmd=ignore-glob), which can be [overridden](https://www.fossil-scm.org/fossil/help?cmd=settings) by a *file* called `.fossil-settings/ignore-glob` (relative to the root of the working directory).

It would be nice if that option even just opened the `.fossil-settings/ignore-glob` file, if it already existed; or asked to create it if it didn’t. Even better would be if it added the untracked file's relative path at the end of the `ignore-glob` file after opening it.

**Comment by koog1000** [comment]
I'll get this done early next week, I've got a busy weekend. But just wanted to let you know I appreciate you making the issues.

**Comment by koog1000** [comment]
check commit 0b95268, tested and working with Windows so far.

**Comment by vor0nwe** [comment]
Ah, I expected it in the context menu, but it's the ‘rollback’ icon instead. No problem, that works too. Although perhaps the order could be made the same as the rollback/add icons for Changes and Staged file types? This one has them reversed, so add/ignore instead of ignore/add.

It also works fine with ‘ignore-glob’ having a non-versionable setting as well (and no `.fossil-settings/ignore-glob.no-warn` file); I expect the `--no-warnings` flag is passed.

**Comment by vor0nwe** [comment]
Isn’t there an icon like ⛔ or 🚫 you could use? "➖" suggests removing the file. Or maybe a crossed-out eye, to symbolize hiding from view (as opposed to removing)?

If the git extension only shows the "ignore" option in the context menu, I think the fossil extension should at least have in the context menu as well, so people used to looking there (like I did) will find it. But the icon-button is a nice extra.

**Comment by koog1000** [comment]
With v0.0.10 I went the route of git and only put the option to ignore the file in the context menu.
