### ISSUE TITLE
After commit, refresh open file diffs

### ISSUE THREAD

**Issue by vor0nwe** [koog1000/vscode-fossil#9]
In 0.0.9, left-clicking on a file in the Version Control pane opens a file diff showing the differences between the file in the repository and the one in the working directory. Very handy. When doing a pull, this gets updated, so the diff is still up-to-date. But after a commit (even of that same file), the file diff _isn’t_ updated, and still shows the differences that have by now been committed.

Ideally, any open file diff should be refreshed after a commit.

**Comment by koog1000** [comment]
I haven't forgotten about this. Spent some time on it in the last week. It is really highlighting that I don't know what I am doing. The file diffs are created, and on a commit I am generating new diffs but vscode isn't updating. I'm not sure how to tell vscode that the diff file (which is not a file on disk) has changed.

**Comment by koog1000** [comment]
Didn't mean to close this before commenting. Finally got some time to figure this out, just submitted a version 0.0.10 [2b2f1b9f97ede8dec3ea01310df1f4b2ab22af0d] that fixes this issue. Should be up in vscode marketplace in a few minutes.

**Comment by vor0nwe** [comment]
Confirming this fixes the problem. Thanks!
